ALTER TABLE "BonusBalance"
  ADD COLUMN IF NOT EXISTS "requiresDeposit" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "depositActivated" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "activationDepositAmount" DECIMAL(16,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "maxCashout" DECIMAL(16,2),
  ADD COLUMN IF NOT EXISTS "wagerMultiplier" INTEGER NOT NULL DEFAULT 6,
  ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
