ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "buttonSize" INTEGER DEFAULT 14;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "titleMobileSize" INTEGER;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "descMobileSize" INTEGER;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "buttonMobileSize" INTEGER;
