ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "buttonColor" TEXT;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "buttonTextColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "secondaryButtonColor" TEXT;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "secondaryButtonTextColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "secondaryButtonOpacity" INTEGER NOT NULL DEFAULT 20;
