ALTER TABLE "WcOddsEvent" ADD COLUMN IF NOT EXISTS "homeCompetitorId" INTEGER;
ALTER TABLE "WcOddsEvent" ADD COLUMN IF NOT EXISTS "awayCompetitorId" INTEGER;
ALTER TABLE "WcOddsEvent" ADD COLUMN IF NOT EXISTS "hasBroadcast" BOOLEAN NOT NULL DEFAULT false;
