-- AlterTable
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "titleMobilePosXPct" INTEGER;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "titleMobilePosYPct" INTEGER;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "descMobilePosXPct" INTEGER;
ALTER TABLE "slide" ADD COLUMN IF NOT EXISTS "descMobilePosYPct" INTEGER;
