/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * One X: Affiliate Program Module
 * The API for One X Project's Affiliate Program
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as isomorphicFetch from "isomorphic-fetch";
import * as url from "url";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    // @ts-ignore
    protected configuration: Configuration;

    constructor(
        configuration?: Configuration,
        protected basePath: string = BASE_PATH,
        protected fetch: FetchAPI = isomorphicFetch,
    ) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 *
 * @export
 * @interface AffiliateProgramLoginRequest
 */
export interface AffiliateProgramLoginRequest {
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramLoginRequest
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramLoginRequest
     */
    password: string;
}
/**
 *
 * @export
 * @interface AffiliateProgramLoginResponse
 */
export interface AffiliateProgramLoginResponse {
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramLoginResponse
     */
    access_token: string;
    /**
     *
     * @type {AffiliateProgramUser}
     * @memberof AffiliateProgramLoginResponse
     */
    user: AffiliateProgramUser;
}
/**
 *
 * @export
 * @interface AffiliateProgramProfileUpdateRequest
 */
export interface AffiliateProgramProfileUpdateRequest {
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    type: AffiliateProgramProfileUpdateRequest.TypeEnum;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    phone_number: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    telegram: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    whatsapp: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    skype: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    password: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramProfileUpdateRequest
     */
    traffic_source: string;
}

/**
 * @export
 * @namespace AffiliateProgramProfileUpdateRequest
 */
export namespace AffiliateProgramProfileUpdateRequest {
    /**
     * @export
     * @enum {string}
     */
    export enum TypeEnum {
        REVSHARE = <any>"REVSHARE",
        CPA = <any>"CPA",
    }
}
/**
 *
 * @export
 * @interface AffiliateProgramRegisterRequest
 */
export interface AffiliateProgramRegisterRequest {
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    type: AffiliateProgramRegisterRequest.TypeEnum;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    phone_number: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    telegram: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    whatsapp: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    skype: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    password: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    traffic_source: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramRegisterRequest
     */
    currency: string;
}

/**
 * @export
 * @namespace AffiliateProgramRegisterRequest
 */
export namespace AffiliateProgramRegisterRequest {
    /**
     * @export
     * @enum {string}
     */
    export enum TypeEnum {
        REVSHARE = <any>"REVSHARE",
        CPA = <any>"CPA",
    }
}
/**
 *
 * @export
 * @interface AffiliateProgramUser
 */
export interface AffiliateProgramUser {
    /**
     *
     * @type {number}
     * @memberof AffiliateProgramUser
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    type: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    phone_number: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    telegram: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    whatsapp: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    skype: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    traffic_source: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    affiliateUrl: string;
    /**
     *
     * @type {I}
     * @memberof AffiliateProgramUser
     */
    percent: I;
    /**
     *
     * @type {I}
     * @memberof AffiliateProgramUser
     */
    balance: I;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    created_at: string;
    /**
     *
     * @type {string}
     * @memberof AffiliateProgramUser
     */
    updated_at: string;
}
/**
 *
 * @export
 * @interface HttpException
 */
export interface HttpException {
    /**
     *
     * @type {Array<string>}
     * @memberof HttpException
     */
    message: Array<string>;
    /**
     *
     * @type {string}
     * @memberof HttpException
     */
    error: string;
    /**
     *
     * @type {number}
     * @memberof HttpException
     */
    statusCode: number;
}
/**
 *
 * @export
 * @interface I
 */
export interface I {}
/**
 * AffiliateProgramApi - fetch parameter creator
 * @export
 */
export const AffiliateProgramApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {AffiliateProgramLoginRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerLogin(body: AffiliateProgramLoginRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError(
                    "body",
                    "Required parameter body was null or undefined when calling profileControllerLogin.",
                );
            }
            const localVarPath = `/affiliate-program/sign-in`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: "POST" }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter["Content-Type"] = "application/json";

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization =
                <any>"AffiliateProgramLoginRequest" !== "string" ||
                localVarRequestOptions.headers["Content-Type"] === "application/json";
            localVarRequestOptions.body = needsSerialization ? JSON.stringify(body || {}) : body || "";

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {AffiliateProgramRegisterRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerRegister(body: AffiliateProgramRegisterRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError(
                    "body",
                    "Required parameter body was null or undefined when calling profileControllerRegister.",
                );
            }
            const localVarPath = `/affiliate-program/sign-up`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: "POST" }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter["Content-Type"] = "application/json";

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization =
                <any>"AffiliateProgramRegisterRequest" !== "string" ||
                localVarRequestOptions.headers["Content-Type"] === "application/json";
            localVarRequestOptions.body = needsSerialization ? JSON.stringify(body || {}) : body || "";

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {AffiliateProgramProfileUpdateRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerUpdateProfile(body: AffiliateProgramProfileUpdateRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError(
                    "body",
                    "Required parameter body was null or undefined when calling profileControllerUpdateProfile.",
                );
            }
            const localVarPath = `/affiliate-program/user`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: "PATCH" }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required

            localVarHeaderParameter["Content-Type"] = "application/json";

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization =
                <any>"AffiliateProgramProfileUpdateRequest" !== "string" ||
                localVarRequestOptions.headers["Content-Type"] === "application/json";
            localVarRequestOptions.body = needsSerialization ? JSON.stringify(body || {}) : body || "";

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerUser(options: any = {}): FetchArgs {
            const localVarPath = `/affiliate-program/user`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: "GET" }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};

/**
 * AffiliateProgramApi - functional programming interface
 * @export
 */
export const AffiliateProgramApiFp = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {AffiliateProgramLoginRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerLogin(
            body: AffiliateProgramLoginRequest,
            options?: any,
        ): (fetch?: FetchAPI, basePath?: string) => Promise<AffiliateProgramLoginResponse> {
            const localVarFetchArgs = AffiliateProgramApiFetchParamCreator(configuration).profileControllerLogin(
                body,
                options,
            );
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         *
         * @param {AffiliateProgramRegisterRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerRegister(
            body: AffiliateProgramRegisterRequest,
            options?: any,
        ): (fetch?: FetchAPI, basePath?: string) => Promise<AffiliateProgramLoginResponse> {
            const localVarFetchArgs = AffiliateProgramApiFetchParamCreator(configuration).profileControllerRegister(
                body,
                options,
            );
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         *
         * @param {AffiliateProgramProfileUpdateRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerUpdateProfile(
            body: AffiliateProgramProfileUpdateRequest,
            options?: any,
        ): (fetch?: FetchAPI, basePath?: string) => Promise<AffiliateProgramUser> {
            const localVarFetchArgs = AffiliateProgramApiFetchParamCreator(
                configuration,
            ).profileControllerUpdateProfile(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerUser(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AffiliateProgramUser> {
            const localVarFetchArgs =
                AffiliateProgramApiFetchParamCreator(configuration).profileControllerUser(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    };
};

/**
 * AffiliateProgramApi - factory interface
 * @export
 */
export const AffiliateProgramApiFactory = function (
    configuration?: Configuration,
    fetch?: FetchAPI,
    basePath?: string,
) {
    return {
        /**
         *
         * @param {AffiliateProgramLoginRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerLogin(body: AffiliateProgramLoginRequest, options?: any) {
            return AffiliateProgramApiFp(configuration).profileControllerLogin(body, options)(fetch, basePath);
        },
        /**
         *
         * @param {AffiliateProgramRegisterRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerRegister(body: AffiliateProgramRegisterRequest, options?: any) {
            return AffiliateProgramApiFp(configuration).profileControllerRegister(body, options)(fetch, basePath);
        },
        /**
         *
         * @param {AffiliateProgramProfileUpdateRequest} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerUpdateProfile(body: AffiliateProgramProfileUpdateRequest, options?: any) {
            return AffiliateProgramApiFp(configuration).profileControllerUpdateProfile(body, options)(fetch, basePath);
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileControllerUser(options?: any) {
            return AffiliateProgramApiFp(configuration).profileControllerUser(options)(fetch, basePath);
        },
    };
};

/**
 * AffiliateProgramApi - object-oriented interface
 * @export
 * @class AffiliateProgramApi
 * @extends {BaseAPI}
 */
export class AffiliateProgramApi extends BaseAPI {
    /**
     *
     * @param {AffiliateProgramLoginRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AffiliateProgramApi
     */
    public profileControllerLogin(body: AffiliateProgramLoginRequest, options?: any) {
        return AffiliateProgramApiFp(this.configuration).profileControllerLogin(body, options)(
            this.fetch,
            this.basePath,
        );
    }

    /**
     *
     * @param {AffiliateProgramRegisterRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AffiliateProgramApi
     */
    public profileControllerRegister(body: AffiliateProgramRegisterRequest, options?: any) {
        return AffiliateProgramApiFp(this.configuration).profileControllerRegister(body, options)(
            this.fetch,
            this.basePath,
        );
    }

    /**
     *
     * @param {AffiliateProgramProfileUpdateRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AffiliateProgramApi
     */
    public profileControllerUpdateProfile(body: AffiliateProgramProfileUpdateRequest, options?: any) {
        return AffiliateProgramApiFp(this.configuration).profileControllerUpdateProfile(body, options)(
            this.fetch,
            this.basePath,
        );
    }

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AffiliateProgramApi
     */
    public profileControllerUser(options?: any) {
        return AffiliateProgramApiFp(this.configuration).profileControllerUser(options)(this.fetch, this.basePath);
    }
}
