/**
 * One X: Affiliate Program Module
 * The API for One X Project's Affiliate Program
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AffiliateProgramApi", () => {
  let instance: api.AffiliateProgramApi
  beforeEach(function() {
    instance = new api.AffiliateProgramApi(config)
  });

  test("profileControllerLogin", () => {
    const body: api.AffiliateProgramLoginRequest = undefined
    return expect(instance.profileControllerLogin(body, {})).resolves.toBe(null)
  })
  test("profileControllerRegister", () => {
    const body: api.AffiliateProgramRegisterRequest = undefined
    return expect(instance.profileControllerRegister(body, {})).resolves.toBe(null)
  })
  test("profileControllerUpdateProfile", () => {
    const body: api.AffiliateProgramProfileUpdateRequest = undefined
    return expect(instance.profileControllerUpdateProfile(body, {})).resolves.toBe(null)
  })
  test("profileControllerUser", () => {
    return expect(instance.profileControllerUser({})).resolves.toBe(null)
  })
})

